# Practical 1: Position and Orientation

We first import the required dependencies

In [1]:
# import libraries we need
import numpy as np

# Exercises

Complete each one of the following programming exercises and submit your solution by the deadline specified on Moodle

### Homogeneous transformation in 2D (3 points)

Given an angle $\theta$ and two displacements $d_x$ and $d_y$, code the corresponding homogeneous transformation matrix

In [2]:
def get_homogeneous_transform_2d(theta, dx, dy):
    
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    
    #TODO: construct the matrix tr -------------------------------
    tr = np.eye(3)
    tr[0:2, :] = [
        [cos_theta, -sin_theta, dx],
        [sin_theta, cos_theta, dy],
    ]
    #ENDTODO -----------------------------------------------------
    
    return tr

We now test the implemented 2D homogeneous transformation with $\theta = \pi/2$, $dx = 5$ and $dy = 5$. Note that we are calling `np.round` because of the numerical error, such as `np.cos(np.pi/2) = 6.123233995736766e-17` instead of being equal to 0.

In [11]:
np.round(get_homogeneous_transform_2d(np.pi/2, 5, 5), 2)

array([[ 0., -1.,  5.],
       [ 1.,  0.,  5.],
       [ 0.,  0.,  1.]])

Expected output: 
```
array([[ 0., -1.,  5.],
       [ 1.,  0.,  5.],
       [ 0.,  0.,  1.]])
```

### Composition of homogeneous transformations  (4 points)

<!-- <img src="Practical1_Support/images/Exercise2_Example.png"> -->
<img src="https://drive.google.com/uc?id=1dBXMNwNbwXsrnBRUwscGXHvh3OlvzPol">

Suppose that the location of a robot (dashed frame) with respect to the world frame (solid frame) is given by the following sequence of transformations:
- A rotation by an angle $\alpha$ (in radians) about the current $z$-axis
- A rotation by an angle $\beta$ (in radians) about the current $x$-axis
- A translation of $b$ units along the current $y$-axis

The robot has a camera (dotted frame) whose location relative to the robot is given by:
- A translation of $c$ units along the current $z$-axis
- A rotation by an angle $\gamma$ (in radians) about the current $y$-axis

Given the coordinates of a points $p_c$ (light blue dot) in the camera frame, determine the coordinates of the same point in the robot's frame and the world frame. **Note that**: the image does not reflect the proper order of transformation, it is purely to visualize solid, dotted, and dashed line.

In [12]:
def get_point_in_robot_frame(point_c=np.array([0,0,1]), gamma=0, disp_c=0):
    
    # Represent point_c in homogeneous form
    homogeneous_point_c = np.hstack([point_c, 1])
    
    #TODO: Define trl_cam_rob to encode translation by disp_c--------
    trl_cam_rob = np.eye(4)
    trl_cam_rob[2, -1] = disp_c 
    #ENDTODO --------------------------------------------------------

    #TODO: Define rot_cam_rob to encode rotation defined by gamma----
    rot_cam_rob = np.eye(4)
    rot_cam_rob[0, 0:3] = [np.cos(gamma), 0, np.sin(gamma)]
    rot_cam_rob[2, 0:3] = [-np.sin(gamma), 0, np.cos(gamma)]
    #ENDTODO -------------------------------------------------------- 
    
    #TODO: Define final_tr as the composed transformation from gamma and disp_c
    final_tr = trl_cam_rob @ rot_cam_rob
    #ENDTODO
    
    # Apply transformation to determine coordinates of point_c in robot frame
    point_r = np.matmul(final_tr, homogeneous_point_c)[:3]
    
    return point_r

def get_point_in_world_frame(point_c=np.array([0,0,1]),
                                alpha=0, beta=0, gamma=0, 
                                disp_c=0, disp_b=0):
    
    # Get point in robot frame
    point_r = get_point_in_robot_frame(point_c, gamma, disp_c)
    
    # Represent point_r in homogeneous form
    homogeneous_point_r = np.hstack([point_r, 1])
    
    #TODO: Define rot_z to encode rotation defined by alpha----------
    rot_z = np.eye(4)
    rot_z[0:2, 0:3] = [
        [np.cos(alpha), -np.sin(alpha), 0],
        [np.sin(alpha), np.cos(alpha), 0]
    ]
    #ENDTODO --------------------------------------------------------
    
    #TODO: Define rot_x to encode rotation defined by beta-----------
    rot_x = np.eye(4)
    rot_x[1:3, 0:3] = [
        [0, np.cos(beta), -np.sin(beta)],
        [0, np.sin(beta), np.cos(beta)]
    ]
    #ENDTODO --------------------------------------------------------

    #TODO: Define trl_cam_world to encode translation by disp_b------
    trl_rob_world = np.eye(4)
    trl_rob_world[1, - 1] = disp_b
    #ENDTODO --------------------------------------------------------
    
    #TODO: compose effect of alpha, beta, disp_b into final_tr-------
    final_tr = rot_z @ rot_x @ trl_rob_world
    #ENDTODO --------------------------------------------------------
    
    # Apply transformation to determine coordinates of point_r in world frame
    point_w = np.matmul(final_tr, homogeneous_point_r)[:3]
    
    return point_w

We now test the implemented 3D homogeneous transformation with a point $p_c$ in camera frame, with coodinate $x = 0, y = 1, z = 3$. Where would that point be in: 
- robot frame?
- world frame?

In [13]:
print(np.round(get_point_in_robot_frame(point_c=np.array([0, 1, 3]), gamma=0, disp_c=2)))
print(np.round(get_point_in_world_frame(point_c=np.array([0, 1, 3]), gamma=0, disp_c=2, alpha=0, beta=0, disp_b=-1)))

[0. 1. 5.]
[0. 0. 5.]


Expected output:
```
[0. 1. 5.]
[0. 0. 5.]
```

# Grading

Test cases for giving marks:
- `q1`: Assess the `get_homogeneous_transform_2d` function (3 points)
- `q2_robot`: Assess the `get_point_in_robot_frame` function (2 points)
- `q2_world`: Assess the `get_point_in_world_frame` function (2 points)

In [6]:
import otter
grader = otter.Notebook(tests_dir = "Practical01_Support/tests")
grader.check_all()

q1 results: All test cases passed!

q2_robot results: All test cases passed!

q2_world results: All test cases passed!

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=325ba0f6-b44d-4215-8ebd-43ced8420cc3' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>